### ISSUE TITLE
Dependency json-joy has changed project structure

### ISSUE THREAD

**Issue by robmadole** [launchscout/phx-live-state#4]
It looks like `json-joy` has refactored their build a bit. After installing `phx-live-state` I got the following error:

```
[info] Running TodoAppWeb.Endpoint with Bandit 1.5.7 at 127.0.0.1:4000 (http)
[info] Access TodoAppWeb.Endpoint at http://localhost:4000
[watch] build finished, watching for changes...
✘ [ERROR] Could not resolve "json-joy/esm/json-patch"

    node_modules/phx-live-state/build/src/LiveState.js:1:27:
      1 │ import { applyPatch } from 'json-joy/esm/json-patch';
        ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "json-joy/esm/json-patch" as external to exclude it from the bundle, which will remove this error.
```

The 16.x major version doesn't have an `esm` directory after installed. I pinned it back to `^11.0` in my `package.json` to get this fixed up temporarily.

Seems like the best way forward is to update the import here:

https://github.com/launchscout/phx-live-state/blob/main/src/LiveState.ts#L1

To be this:

```js
import { applyPatch } from 'json-joy/lib/json-patch';
```

**Comment by superchris** [comment]
Hey thanks for reporting this! Making this change seems to make my tests very unhappy, still tracking down exactly why this is as it certainly looks correct to me too. I'll see if I can get to the bottom of it and get a fix out soon.

**Comment by superchris** [comment]
Ok, after digging in it appears that json-joy has [gone away from publishing ESM modules](https://github.com/streamich/json-joy/issues/626). This makes it unusable for me, so I'll need to pin the dependency to an old version for now and either republish an esm version of json-joy myself or switch to an alternate implementation. Quite frustrating TBH.

**Comment by robmadole** [comment]
@superchris yeah weird decision! Sounds like they didn't see a reason for it. So maybe you and a few others piping in will convince them. I guess you could fork it and modify/layer another .tsconfig but that's gross. Shoot, _they_ could fork a `json-joy-esm` if they wanted. Just weird.

**Comment by superchris** [comment]
I released a new version of `phx-live-state` with json-joy pinned at `^11.0`. My thought is to make another issue if to track either forking json-joy or going with an alternate impl if there is a reason we need/want to do that.
